name: Docker Image CI

on:
  push:
    branches: [ dependabot/maven/my-app/junit-junit-4.13.1 ]
  pull_request:
    branches: [ dependabot/maven/my-app/junit-junit-4.13.1 ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
